### PR TITLE
Add hard set functionality

### PR DESCRIPTION
**Pull request by sunchayn**
Hey there, i came across the need to make the configuration file read/write. I'm building a configurable app. Anyway, the php config libraries out there are run-time only.So i forked this library and added the desired functionality. I think it will be useful for someone else.

*currently it support phpLoader only.*

### CODE REVIEW

**Comment by shadowhand** [comment]
My gut reaction is that this is really unsafe and should not be done. Editable configuration should be stored in a database.

**Comment by sunchayn** [comment]
Is it possible to provide a scenario when it would be unsafe and how ? maybe we can find a secure solution for that.

Some use cases require using file system storage as a dynamic configuration instead of a database. For example, my use case is a database adminstration app. The developer needs to select and configure the database from the app UI and later on the app uses the same file to connect to the database, so my app's related configuration should be database free.

**Comment by shadowhand** [comment]
@mazentouati I think showing the config file that should be uploaded to the server would be a reasonable approach. Even systems like WordPress don't allow modification of DB credentials via the web UI.

**Comment by sunchayn** [comment]
Worth noting that what i meant by database administration app is a tool like phpmyadmin. What i building is a toolkit designed for developers to use in their local machines. Anyway, i'll use the forked version instead, thanks.

**Comment by shadowhand** [comment]
PHPMyAdmin doesn't allow setting DB parameters by web UI either. It's just not safe, because any web process can overwrite.

**Comment by sunchayn** [comment]
Well as far as i know, you can configure phpmyadmin using the setup script. Wordpress and other CMS does it too during the installation process. Though, i don't have the option to use a database for configuration in my specific case, thanks anyway.

**Pull request closed without merging**
